export const SPELLS = {
  // ── WIZARD / SORCERER / SHARED ──────────────────────────────────────
  "Fire Bolt":           { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Instant",       en:"Ranged spell attack: 1d10 fire.",                                          da:"Afstandsangreb med trylleformular: 1d10 ild." },
  "Ray of Frost":        { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"Hit: 1d8 cold, target speed -10 ft.",                                      da:"Ramt: 1d8 kulde, målets fart -3 m." },
  "Shocking Grasp":      { school:"Evocation",   cast:"1 action",       range:"Touch",            dur:"Instant",       en:"Advantage vs metal armor. Hit: 1d8 lightning, no reactions.",              da:"Fordel mod metalrustning. Ramt: 1d8 lyn, ingen reaktioner." },
  "Mage Hand":           { school:"Conjuration", cast:"1 action",       range:"30 ft",            dur:"1 minute",      en:"Spectral hand, up to 10 lb.",                                              da:"Spektral hånd, op til 5 kg kan manipuleres på afstand." },
  "Minor Illusion":      { school:"Illusion",    cast:"1 action",       range:"30 ft",            dur:"1 minute",      en:"Sound or image. INT check to disbelieve.",                                 da:"Skab en lyd eller et billede. INT-check for at gennemskue illusionen." },
  "Prestidigitation":    { school:"Transmutation",cast:"1 action",      range:"10 ft",            dur:"Up to 1 hr",    en:"Minor magical tricks.",                                                    da:"Små magiske tricks." },
  "Magic Missile":       { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Instant",       en:"3 darts, 1d4+1 force each, auto-hit.",                                     da:"3 magiske projektiler, 1d4+1 kraft hver, rammer automatisk." },
  "Shield":              { school:"Abjuration",  cast:"1 reaction",     range:"Self",             dur:"1 round",       en:"+5 AC. Immune to Magic Missile.",                                          da:"+5 SK. Immun mod Magic Missile." },
  "Mage Armor":          { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"8 hours",       en:"AC = 13+DEX for unarmored creature.",                                      da:"SK = 13 + DEX for en skabning uden rustning." },
  "Burning Hands":       { school:"Evocation",   cast:"1 action",       range:"15-ft cone",       dur:"Instant",       en:"DEX save or 3d6 fire.",                                                    da:"DEX-redning ellers 3d6 ild." },
  "Charm Person":        { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"1 hour",        en:"WIS save or charmed.",                                                     da:"VIS-redning ellers betaget." },
  "Sleep":               { school:"Enchantment", cast:"1 action",       range:"90 ft",            dur:"1 minute",      en:"5d8 HP worth of creatures fall asleep.",                                   da:"Skabninger med op til 5d8 HP sammenlagt falder i søvn." },
  "Thunderwave":         { school:"Evocation",   cast:"1 action",       range:"Self (15-ft cube)", dur:"Instant",      en:"CON save or 2d8 thunder + pushed 10 ft.",                                  da:"KON-redning ellers 2d8 torden + skubbet 3 m." },
  "Misty Step":          { school:"Conjuration", cast:"1 bonus action", range:"Self",             dur:"Instant",       en:"Teleport up to 30 ft.",                                                    da:"Teleporter op til 9 m." },
  "Hold Person":         { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"WIS save or humanoid paralyzed.",                                          da:"VIS-redning ellers bliver en humanoid lammet." },
  "Invisibility":        { school:"Illusion",    cast:"1 action",       range:"Touch",            dur:"Conc. 1 hr",    en:"Target invisible until it attacks or casts.",                               da:"Målet er usynligt, indtil det angriber eller kaster en trylleformular." },
  "Mirror Image":        { school:"Illusion",    cast:"1 action",       range:"Self",             dur:"1 minute",      en:"3 duplicates absorb attacks.",                                             da:"3 illusionære kopier kan aflede angreb." },
  "Scorching Ray":       { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Instant",       en:"3 rays, 2d6 fire each.",                                                   da:"3 stråler, 2d6 ild hver." },
  "Shatter":             { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"CON save or 3d8 thunder.",                                                 da:"KON-redning ellers 3d8 torden." },
  "Suggestion":          { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"Conc. 8 hr",    en:"WIS save or follow a suggestion.",                                         da:"VIS-redning ellers følg et forslag." },
  "Counterspell":        { school:"Abjuration",  cast:"1 reaction",     range:"60 ft",            dur:"Instant",       en:"Interrupt a spell being cast.",                                            da:"Afbryd en trylleformel der kastes." },
  "Fireball":            { school:"Evocation",   cast:"1 action",       range:"150 ft",           dur:"Instant",       en:"20-ft radius. DEX save or 8d6 fire.",                                      da:"6 m radius. DEX-redning ellers 8d6 ild." },
  "Fly":                 { school:"Transmutation",cast:"1 action",      range:"Touch",            dur:"Conc. 10 min",  en:"Flying speed 60 ft.",                                                      da:"Flyvehastighed 18 m." },
  "Haste":               { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Conc. 1 min",   en:"Double speed, +2 AC, extra action.",                                       da:"Dobbelt hastighed, +2 SK, ekstra handling." },
  "Lightning Bolt":      { school:"Evocation",   cast:"1 action",       range:"Self (100-ft line)",dur:"Instant",      en:"DEX save or 8d6 lightning.",                                               da:"DEX-redning ellers 8d6 lyn." },
  "Slow":                { school:"Transmutation",cast:"1 action",      range:"120 ft",           dur:"Conc. 1 min",   en:"WIS save or halved speed, -2 AC/DEX.",                                     da:"VIS-redning ellers halvt tempo, -2 SK/DEX." },
  "Fear":                { school:"Illusion",    cast:"1 action",       range:"Self (30-ft cone)", dur:"Conc. 1 min",  en:"WIS save or frightened and flee.",                                         da:"VIS-redning ellers bange og flygter." },
  "Banishment":          { school:"Abjuration",  cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"CHA save or banished.",                                                    da:"KAR-redning ellers forvist." },
  "Greater Invisibility":{ school:"Illusion",    cast:"1 action",       range:"Touch",            dur:"Conc. 1 min",   en:"Invisible even while attacking.",                                          da:"Usynlig selv under angreb og trylleformelskastning." },
  "Ice Storm":           { school:"Evocation",   cast:"1 action",       range:"300 ft",           dur:"Instant",       en:"20-ft radius, 2d8 bludgeoning+4d6 cold.",                                  da:"6 m radius, 2d8 slag + 4d6 kulde." },
  "Polymorph":           { school:"Transmutation",cast:"1 action",      range:"60 ft",            dur:"Conc. 1 hr",    en:"WIS save or transform into beast.",                                        da:"VIS-redning ellers forvandlet til et dyr." },
  "Confusion":           { school:"Enchantment", cast:"1 action",       range:"90 ft",            dur:"Conc. 1 min",   en:"WIS save or act randomly.",                                                da:"VIS-redning ellers handler tilfældigt." },
  "Cone of Cold":        { school:"Evocation",   cast:"1 action",       range:"Self (60-ft cone)", dur:"Instant",      en:"CON save or 8d8 cold.",                                                    da:"KON-redning ellers 8d8 kulde." },
  "Hold Monster":        { school:"Enchantment", cast:"1 action",       range:"90 ft",            dur:"Conc. 1 min",   en:"WIS save or any creature paralyzed.",                                      da:"VIS-redning ellers bliver en skabning lammet." },
  "Cloudkill":           { school:"Conjuration", cast:"1 action",       range:"120 ft",           dur:"Conc. 10 min",  en:"20-ft sphere toxic fog, 5d8 poison per turn.",                             da:"6 m kugle giftig tåge, 5d8 gift pr. tur." },
  "Dominate Person":     { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"WIS save or control a humanoid.",                                          da:"VIS-redning ellers kontrollerer du en humanoid." },
  "Dancing Lights":      { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Conc. 1 min",   en:"4 floating lights.",                                                       da:"4 svævende lys." },
  "Darkness":            { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Conc. 10 min",  en:"15-ft magical darkness.",                                                  da:"4,5 m magisk mørke." },
  "Vampiric Touch":      { school:"Necromancy",  cast:"1 action",       range:"Self",             dur:"Conc. 1 min",   en:"3d6 necrotic; regain half as HP.",                                         da:"3d6 nekrotisk; genvind halvdelen som HP." },
  "Hypnotic Pattern":    { school:"Illusion",    cast:"1 action",       range:"120 ft",           dur:"Conc. 1 min",   en:"WIS save or incapacitated.",                                               da:"VIS-redning ellers handlingsudygtig." },
  "Major Image":         { school:"Illusion",    cast:"1 action",       range:"120 ft",           dur:"Conc. 10 min",  en:"20-ft cube illusion with sound and smell.",                                da:"6 m kubeillusion med lyd og lugt." },
  "Sending":             { school:"Evocation",   cast:"1 action",       range:"Unlimited",        dur:"1 round",       en:"25-word message to known creature.",                                       da:"25-ords besked til en kendt skabning." },
  "Dimension Door":      { school:"Conjuration", cast:"1 action",       range:"500 ft",           dur:"Instant",       en:"Teleport self + one creature up to 500 ft.",                               da:"Teleporter dig + én skabning op til 150 m." },
  "Hallucinatory Terrain":{ school:"Illusion",   cast:"10 minutes",     range:"300 ft",           dur:"24 hours",      en:"Terrain looks like another terrain type.",                                  da:"Terræn ser ud som en anden terræntype." },
  "Silence":             { school:"Illusion",    cast:"1 action",       range:"120 ft",           dur:"Conc. 10 min",  en:"20-ft sphere of magical silence.",                                         da:"6 m kugle magisk stilhed." },
  // ── CLERIC ──────────────────────────────────────────────────────────
  "Sacred Flame":        { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"DEX save or 1d8 radiant. Scales at 5/11/17.",                              da:"DEX-redning ellers 1d8 radiant. Skalerer ved niveau 5/11/17." },
  "Guidance":            { school:"Divination",  cast:"1 action",       range:"Touch",            dur:"1 minute",      en:"No concentration. +1d4 to one ability check.",                             da:"Ingen koncentration. +1d4 til ét evnecheck." },
  "Light":               { school:"Evocation",   cast:"1 action",       range:"Touch",            dur:"1 hour",        en:"Object sheds bright light 20 ft.",                                         da:"Genstand lyser klart 6 m." },
  "Thaumaturgy":         { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Up to 1 min",   en:"Minor wonder effect.",                                                     da:"Lille vidundereffekt." },
  "Toll the Dead":       { school:"Necromancy",  cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"WIS save or 1d8 (1d12 if wounded) necrotic.",                              da:"VIS-redning ellers 1d8 (1d12 hvis såret) nekrotisk." },
  "Bless":               { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"Conc. 1 min",   en:"3 creatures add 1d4 to attacks/saves.",                                    da:"3 skabninger tilføjer 1d4 til angreb/redninger." },
  "Command":             { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"1 round",       en:"WIS save or one-word command.",                                            da:"VIS-redning ellers ét ords kommando." },
  "Cure Wounds":         { school:"Evocation",   cast:"1 action",       range:"Touch",            dur:"Instant",       en:"Restore 2d8+mod HP.",                                                      da:"Gendan 2d8+mod HP." },
  "Guiding Bolt":        { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"1 round",       en:"4d6 radiant, next attack has advantage.",                                  da:"4d6 radiant, næste angreb mod målet har fordel." },
  "Healing Word":        { school:"Evocation",   cast:"1 bonus action", range:"60 ft",            dur:"Instant",       en:"Restore 2d4+mod HP.",                                                      da:"Gendan 2d4+mod HP." },
  "Inflict Wounds":      { school:"Necromancy",  cast:"1 action",       range:"Touch",            dur:"Instant",       en:"Melee spell attack: 3d10 necrotic.",                                       da:"Melee-stavangreb: 3d10 nekrotisk." },
  "Shield of Faith":     { school:"Abjuration",  cast:"1 bonus action", range:"60 ft",            dur:"Conc. 10 min",  en:"+2 AC.",                                                                   da:"+2 SK." },
  "Aid":                 { school:"Abjuration",  cast:"1 action",       range:"30 ft",            dur:"8 hours",       en:"3 creatures gain +5 max HP.",                                              da:"3 skabninger får +5 maks. HP." },
  "Lesser Restoration":  { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"Instant",       en:"End one condition or disease.",                                            da:"Afslut én tilstand eller sygdom." },
  "Prayer of Healing":   { school:"Evocation",   cast:"10 minutes",     range:"30 ft",            dur:"Instant",       en:"6 creatures regain 2d8+mod HP.",                                           da:"6 skabninger genvinder 2d8+mod HP." },
  "Spiritual Weapon":    { school:"Evocation",   cast:"1 bonus action", range:"60 ft",            dur:"1 minute",      en:"Spectral weapon: 1d8+mod force per turn.",                                 da:"Spektralvåben: 1d8+mod kraft pr. tur." },
  "Animate Dead":        { school:"Necromancy",  cast:"1 minute",       range:"10 ft",            dur:"24 hours",      en:"Create undead servant.",                                                   da:"Skab en udød tjener." },
  "Daylight":            { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"1 hour",        en:"60-ft radius bright light.",                                               da:"18 m radius klart lys." },
  "Dispel Magic":        { school:"Abjuration",  cast:"1 action",       range:"120 ft",           dur:"Instant",       en:"End one spell 3rd level or lower.",                                        da:"Afslut én trylleformel 3. niveau eller lavere." },
  "Spirit Guardians":    { school:"Conjuration", cast:"1 action",       range:"Self (15-ft radius)",dur:"Conc. 10 min", en:"WIS save or 3d8 radiant/necrotic.",                                       da:"VIS-redning ellers 3d8 radiant/nekrotisk." },
  "Remove Curse":        { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"Instant",       en:"End all curses on target.",                                                da:"Afslut alle forbandelser på målet." },
  "Death Ward":          { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"8 hours",       en:"Drop to 1 HP instead of 0 once.",                                          da:"Fald til 1 HP i stedet for 0 – én gang." },
  "Freedom of Movement": { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"1 hour",        en:"Ignore difficult terrain and restraints.",                                 da:"Ignorer svært terræn og indsnævringer." },
  "Guardian of Faith":   { school:"Conjuration", cast:"1 action",       range:"30 ft",            dur:"8 hours",       en:"20 radiant to hostiles within 10 ft.",                                     da:"20 radiant til fjendtlige inden for 3 m." },
  "Flame Strike":        { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"DEX save or 4d6 fire+4d6 radiant.",                                        da:"DEX-redning ellers 4d6 ild+4d6 radiant." },
  "Greater Restoration": { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"Instant",       en:"End major condition or curse.",                                            da:"Afslut større tilstand eller forbandelse." },
  "Mass Cure Wounds":    { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"6 creatures regain 3d8+mod HP.",                                           da:"6 skabninger genvinder 3d8+mod HP." },
  "Raise Dead":          { school:"Necromancy",  cast:"1 hour",         range:"Touch",            dur:"Instant",       en:"Return dead creature to life (500gp diamond).",                            da:"Bring en død skabning til live (500gp diamant)." },
  "Bane":                { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"Conc. 1 min",   en:"CHA save or -1d4 to attacks/saves.",                                       da:"KAR-redning ellers -1d4 på angreb/redninger." },
  "Sanctuary":           { school:"Abjuration",  cast:"1 bonus action", range:"30 ft",            dur:"1 minute",      en:"WIS save or attackers must choose new target.",                            da:"VIS-redning: angribere skal vælge et nyt mål." },
  "Augury":              { school:"Divination",  cast:"1 minute (ritual)",range:"Self",           dur:"Instant",       en:"Weal/woe for action in next 30 min.",                                      da:"Held/uheld for en handling inden for 30 min." },
  "Calm Emotions":       { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"Suppress charm/fright or emotions.",                                       da:"Undertryk betaget/bange eller følelser." },
  "Enhance Ability":     { school:"Transmutation",cast:"1 action",      range:"Touch",            dur:"Conc. 1 hr",    en:"Advantage on one ability checks.",                                         da:"Fordel på ét evne-check." },
  "Find Traps":          { school:"Divination",  cast:"1 action",       range:"120 ft",           dur:"Instant",       en:"Sense traps in line of sight.",                                            da:"Fornem fælder i synslinjen." },
  "Warding Bond":        { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"1 hour",        en:"+1 AC/saves, resistance; you share damage taken.",                         da:"+1 SK/redninger, resistens; du deler modtaget skade." },
  "Zone of Truth":       { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"10 minutes",    en:"CHA save or cannot lie in 15-ft sphere.",                                  da:"KAR-redning ellers kan ikke lyve i 4,5 m kugle." },
  "Beacon of Hope":      { school:"Abjuration",  cast:"1 action",       range:"30 ft",            dur:"Conc. 1 min",   en:"Advantage on WIS saves and death saves.",                                  da:"Fordel på VIS-redninger og dødredninger." },
  "Create Food and Water":{ school:"Conjuration",cast:"1 action",       range:"30 ft",            dur:"Instant",       en:"Create 45 lb food and 30 gallons water.",                                  da:"Skab 20 kg mad og 115 liter vand." },
  "Mass Healing Word":   { school:"Evocation",   cast:"1 bonus action", range:"60 ft",            dur:"Instant",       en:"6 creatures regain 1d4+mod HP.",                                           da:"6 skabninger genvinder 1d4+mod HP." },
  "Meld into Stone":     { school:"Transmutation",cast:"1 action (ritual)",range:"Touch",         dur:"8 hours",       en:"Step into a stone object.",                                                da:"Træd ind i en stengenstand." },
  "Speak with Dead":     { school:"Necromancy",  cast:"1 action",       range:"10 ft",            dur:"10 minutes",    en:"Ask a corpse 5 questions.",                                                da:"Stil et lig 5 spørgsmål." },
  "Water Walk":          { school:"Transmutation",cast:"1 action (ritual)",range:"30 ft",         dur:"1 hour",        en:"Walk across liquid as if solid.",                                          da:"Gå hen over væske som om det er fast grund." },
  "Divination":          { school:"Divination",  cast:"1 action (ritual)",range:"Self",           dur:"Instant",       en:"Truthful reply about event within 7 days.",                                da:"Sandfærdigt svar på begivenhed inden for 7 dage." },
  "Commune":             { school:"Divination",  cast:"1 minute (ritual)",range:"Self",           dur:"1 minute",      en:"Ask deity 3 yes/no questions.",                                            da:"Stil guddom 3 ja/nej-spørgsmål." },
  "Contagion":           { school:"Necromancy",  cast:"1 action",       range:"Touch",            dur:"7 days",        en:"3 failed CON saves = diseased.",                                           da:"3 mislykkede KON-redninger = smittet." },
  "Dispel Evil and Good":{ school:"Abjuration",  cast:"1 action",       range:"Self",             dur:"Conc. 1 min",   en:"Fiends/undead/fey disadvantage attacking you.",                            da:"Fæler/udøde/fey har ulempe til at angribe dig." },
  "Hallow":              { school:"Evocation",   cast:"24 hours",       range:"Touch",            dur:"Until dispelled",en:"60-ft radius hallowed ground.",                                           da:"18 m radius helliget område." },
  "Summon Celestial":    { school:"Conjuration", cast:"1 action",       range:"90 ft",            dur:"Conc. 1 hr",    en:"Summon obedient celestial spirit.",                                        da:"Kald en lydig himmelsk ånd." },
  "Create or Destroy Water":{ school:"Transmutation",cast:"1 action",   range:"30 ft",            dur:"Instant",       en:"Create or destroy 10 gallons of water.",                                   da:"Skab eller ødelæg 40 liter vand." },
  "Detect Evil and Good":{ school:"Divination",  cast:"1 action",       range:"Self",             dur:"Conc. 10 min",  en:"Sense fiends, undead, celestials within 30 ft.",                           da:"Fornem fæler, udøde, himmelske inden for 9 m." },
  "Detect Magic":        { school:"Divination",  cast:"1 action (ritual)",range:"Self",           dur:"Conc. 10 min",  en:"Sense magic within 30 ft.",                                                da:"Fornem magi inden for 9 m." },
  "Detect Poison and Disease":{ school:"Divination",cast:"1 action (ritual)",range:"Self",        dur:"Conc. 10 min",  en:"Sense poison and disease within 30 ft.",                                   da:"Fornem gift og sygdom inden for 9 m." },
  "Purify Food and Drink":{ school:"Transmutation",cast:"1 action (ritual)",range:"10 ft",        dur:"Instant",       en:"Purify food and drink in 5-ft sphere.",                                    da:"Rens mad og drikke i 1,5 m kugle." },
  // ── DRUID ────────────────────────────────────────────────────────────
  "Druidcraft":          { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Instant",       en:"Minor nature effect.",                                                     da:"Lille natureffekt." },
  "Produce Flame":       { school:"Conjuration", cast:"1 action",       range:"Self",             dur:"10 minutes",    en:"Flame: light or hurl for 1d8 fire.",                                       da:"Flamme: lys eller kast for 1d8 ild." },
  "Shillelagh":          { school:"Transmutation",cast:"1 bonus action", range:"Touch",           dur:"1 minute",      en:"No concentration. Weapon uses WIS, damage 1d8+WIS.",                       da:"Ingen koncentration. Våben bruger VIS, skade 1d8+VIS." },
  "Thorn Whip":          { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Instant",       en:"1d6 piercing, pull 10 ft.",                                                da:"1d6 gennemborende skade, træk 3 m." },
  "Animal Friendship":   { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"24 hours",      en:"WIS save or beast charmed.",                                               da:"VIS-redning ellers dyr betaget." },
  "Entangle":            { school:"Conjuration", cast:"1 action",       range:"90 ft",            dur:"Conc. 1 min",   en:"STR save or restrained by weeds.",                                         da:"STY-redning ellers fastholdt af planter." },
  "Faerie Fire":         { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"DEX save or outlined; attacks have advantage.",                            da:"DEX-redning ellers omridset; angreb har fordel." },
  "Goodberry":           { school:"Transmutation",cast:"1 action",      range:"Touch",            dur:"24 hours",      en:"10 berries, each restores 1 HP.",                                          da:"10 bær, hvert gendanner 1 HP." },
  "Speak with Animals":  { school:"Divination",  cast:"1 action (ritual)",range:"Self",           dur:"10 minutes",    en:"Communicate with beasts.",                                                 da:"Kommuniker med dyr." },
  "Barkskin":            { school:"Transmutation",cast:"1 bonus action", range:"Touch",           dur:"1 hour",        en:"No concentration. AC 17.",                                                 da:"Ingen koncentration. SK 17." },
  "Flaming Sphere":      { school:"Conjuration", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"2d6 fire sphere, bonus action move.",                                      da:"2d6 ild kugle, bonushandling flyt." },
  "Moonbeam":            { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Conc. 1 min",   en:"CON save or 2d10 radiant per turn.",                                       da:"KON-redning ellers 2d10 strålende skade pr. tur." },
  "Pass without Trace":  { school:"Abjuration",  cast:"1 action",       range:"Self",             dur:"Conc. 1 hr",    en:"+10 Stealth to you and 10 companions.",                                    da:"+10 til Snigeri for dig og 10 ledsagere." },
  "Spike Growth":        { school:"Transmutation",cast:"1 action",      range:"150 ft",           dur:"Conc. 10 min",  en:"2d4 piercing per 5 ft moved.",                                             da:"2d4 gennemborende skade pr. 1,5 m bevæget." },
  "Call Lightning":      { school:"Conjuration", cast:"1 action",       range:"120 ft",           dur:"Conc. 10 min",  en:"DEX save or 3d10 lightning per turn.",                                     da:"DEX-redning ellers 3d10 lyn pr. tur." },
  "Conjure Animals":     { school:"Conjuration", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 hr",    en:"Summon beasts totaling CR 2.",                                             da:"Kald dyr med samlet FV 2." },
  "Plant Growth":        { school:"Transmutation",cast:"1 action",      range:"150 ft",           dur:"Instant",       en:"100-ft radius difficult terrain.",                                         da:"30 m radius svært terræn." },
  "Blight":              { school:"Necromancy",  cast:"1 action",       range:"30 ft",            dur:"Instant",       en:"CON save or 8d8 necrotic.",                                                da:"KON-redning ellers 8d8 nekrotisk skade." },
  "Insect Plague":       { school:"Conjuration", cast:"1 action",       range:"300 ft",           dur:"Conc. 10 min",  en:"CON save or 4d10 piercing per turn.",                                      da:"KON-redning ellers 4d10 gennemborende skade pr. tur." },
  "Animal Messenger":    { school:"Enchantment", cast:"1 action (ritual)",range:"30 ft",          dur:"24 hours",      en:"Tiny beast delivers 25-word message.",                                     da:"Lille dyr leverer 25-ords besked." },
  "Beast Sense":         { school:"Divination",  cast:"1 action (ritual)",range:"Touch",          dur:"Conc. 1 hr",    en:"See and hear through a beast.",                                            da:"Se og hør gennem et dyr." },
  "Flame Blade":         { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 10 min",  en:"Fire scimitar: 3d6 fire.",                                                 da:"Ild-sabel: 3d6 ild." },
  "Gust of Wind":        { school:"Evocation",   cast:"1 action",       range:"Self",             dur:"Conc. 1 min",   en:"60-ft wind line pushes 15 ft.",                                            da:"18 m vindlinje skubber 4,5 m." },
  "Heat Metal":          { school:"Transmutation",cast:"1 action",      range:"60 ft",            dur:"Conc. 1 min",   en:"Metal glows: 2d8 fire, CON save or drop it.",                              da:"Metal gløder: 2d8 ild, KON-redning ellers slipper målet det." },
  "Locate Object":       { school:"Divination",  cast:"1 action",       range:"Self",             dur:"Conc. 10 min",  en:"Sense direction to known object within 1000 ft.",                          da:"Fornem retning til kendt genstand inden for 300 m." },
  "Locate Animals or Plants":{ school:"Divination",cast:"1 action (ritual)",range:"Self",         dur:"Instant",       en:"Sense nearest named beast or plant within 5 miles.",                       da:"Fornem nærmeste navngivne dyr eller plante inden for 8 km." },
  "Protection from Poison":{ school:"Abjuration",cast:"1 action",       range:"Touch",            dur:"1 hour",        en:"Advantage vs poison, resistance to poison damage.",                        da:"Fordel mod gift, resistens mod giftskade." },
  "Wind Wall":           { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Conc. 1 min",   en:"Wall of wind; 3d8 bludgeoning.",                                           da:"Vindmur; 3d8 slag." },
  "Dominate Beast":      { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"WIS save or control a beast.",                                             da:"VIS-redning ellers kontroller et dyr." },
  "Giant Insect":        { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Conc. 10 min",  en:"Insects become giant versions.",                                           da:"Insekter bliver kæmpeversioner." },
  "Antilife Shell":      { school:"Abjuration",  cast:"1 action",       range:"Self (10-ft radius)",dur:"Conc. 1 hr",  en:"Barrier prevents living creatures entering.",                              da:"Barriere forhindrer levende skabninger i at komme ind." },
  "Reincarnate":         { school:"Transmutation",cast:"1 hour",        range:"Touch",            dur:"Instant",       en:"Restore dead creature in new body.",                                       da:"Gendan en død skabning i et nyt legeme." },
  "Animal Shapes":       { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Conc. 1 day",   en:"Willing creatures become beasts CR 4 or lower.",                           da:"Villige skabninger bliver dyr FV 4 eller lavere." },
  "Earth Tremor":        { school:"Evocation",   cast:"1 action",       range:"10 ft",            dur:"Instant",       en:"DEX save or 1d6 bludgeoning and prone.",                                   da:"DEX-redning ellers 1d6 slag og kastet til jorden." },
  "Commune with Nature": { school:"Divination",  cast:"1 min (ritual)", range:"Self",             dur:"Instant",       en:"Learn 3 facts about nearby terrain.",                                      da:"Lær 3 fakta om det nærliggende terræn." },
  "Speak with Plants":   { school:"Transmutation",cast:"1 action",      range:"Self (30-ft radius)",dur:"10 minutes",  en:"Communicate with plants.",                                                 da:"Kommuniker med planter." },
  // ── WARLOCK ──────────────────────────────────────────────────────────
  "Eldritch Blast":      { school:"Evocation",   cast:"1 action",       range:"120 ft",           dur:"Instant",       en:"1d10 force beam. Hit creature can be pushed 10 ft. More beams at higher levels.", da:"1d10 kraft stråle. Ramt skabning kan skubbes 3 m. Flere stråler ved højere niveauer." },
  "Chill Touch":         { school:"Necromancy",  cast:"1 action",       range:"120 ft",           dur:"1 round",       en:"1d8 necrotic, target cannot regain HP.",                                   da:"1d8 nekrotisk, målet kan ikke genvinde HP." },
  "Armor of Agathys":    { school:"Abjuration",  cast:"1 action",       range:"Self",             dur:"1 hour",        en:"5 temp HP; attacker takes 5 cold.",                                        da:"5 midlertidige HP; angriber tager 5 kulde." },
  "Arms of Hadar":       { school:"Conjuration", cast:"1 action",       range:"Self (10-ft radius)",dur:"Instant",     en:"STR save or 2d6 necrotic, no reactions.",                                  da:"STY-redning ellers 2d6 nekrotisk, ingen reaktioner." },
  "Hex":                 { school:"Enchantment", cast:"1 bonus action", range:"90 ft",            dur:"Conc. 1 hr",    en:"+1d6 necrotic on weapon and spell attacks.",                               da:"+1d6 nekrotisk på våben- og stavangreb." },
  "Hellish Rebuke":      { school:"Evocation",   cast:"1 reaction",     range:"60 ft",            dur:"Instant",       en:"DEX save or 2d10 fire.",                                                   da:"DEX-redning ellers 2d10 ild." },
  "Witch Bolt":          { school:"Evocation",   cast:"1 action",       range:"30 ft",            dur:"Conc. 1 min",   en:"1d12 lightning, sustain for 1d12 per turn.",                               da:"1d12 lyn, oprethold for 1d12 pr. tur." },
  "Hunger of Hadar":     { school:"Conjuration", cast:"1 action",       range:"150 ft",           dur:"Conc. 1 min",   en:"20-ft darkness void: 2d6 cold+2d6 acid.",                                  da:"6 m mørkt tomrum: 2d6 kulde+2d6 syre." },
  "Enthrall":            { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"1 minute",      en:"WIS save or distracted by you.",                                           da:"VIS-redning ellers distraheret af dig." },
  "Compulsion":          { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"Conc. 1 min",   en:"WIS save or must move chosen direction.",                                  da:"VIS-redning ellers tvinges til at bevæge sig en valgt retning." },
  // ── BARD ─────────────────────────────────────────────────────────────
  "Vicious Mockery":     { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"WIS save or 1d6 psychic (scales 2d6/3d6/4d6), disadv on next attack.",     da:"VIS-redning ellers 1d6 psykisk (skalerer), ulempe på næste angreb." },
  "Dissonant Whispers":  { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"WIS save or 3d6 psychic, must flee.",                                      da:"VIS-redning ellers 3d6 psykisk, skal flygte." },
  "Heroism":             { school:"Enchantment", cast:"1 action",       range:"Touch",            dur:"Conc. 1 min",   en:"Immune to frightened; temp HP each turn.",                                 da:"Immun mod bange; midlertidige HP pr. tur." },
  // ── PALADIN ──────────────────────────────────────────────────────────
  "Divine Favor":        { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"+1d4 radiant on weapon hits.",                                             da:"+1d4 radiant på våbenangrebs." },
  "Find Steed":          { school:"Conjuration", cast:"10 minutes",     range:"30 ft",            dur:"Instant",       en:"Summon a spirit steed.",                                                   da:"Kald en ånderidt." },
  "Aura of Vitality":    { school:"Evocation",   cast:"1 action",       range:"Self (30-ft radius)",dur:"Conc. 1 min", en:"Bonus action: restore 2d6 HP to one creature.",                            da:"Bonushandling: gendan 2d6 HP til én skabning." },
  "Revivify":            { school:"Necromancy",  cast:"1 action",       range:"Touch",            dur:"Instant",       en:"Return dead (1 min) to life (300gp diamond).",                             da:"Gendan død (1 min) til live (300gp diamant)." },
  "Compelled Duel":      { school:"Enchantment", cast:"1 bonus action", range:"30 ft",            dur:"Conc. 1 min",   en:"WIS save or must fight only you.",                                         da:"VIS-redning ellers skal kun kæmpe mod dig." },
  "Thunderous Smite":    { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"+2d6 thunder, STR save or prone.",                                         da:"+2d6 torden, STY-redning ellers væltet omkuld." },
  "Wrathful Smite":      { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"+1d6 psychic, WIS save or frightened.",                                    da:"+1d6 psykisk, VIS-redning ellers bange." },
  "Branding Smite":      { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"+2d6 radiant, target cannot be invisible.",                                da:"+2d6 radiant, målet kan ikke være usynligt." },
  "Crusader's Mantle":   { school:"Evocation",   cast:"1 action",       range:"Self",             dur:"Conc. 1 min",   en:"Allies within 30 ft deal +1d4 radiant.",                                   da:"Allierede inden for 9 m gør +1d4 radiant." },
  "Elemental Weapon":    { school:"Transmutation",cast:"1 action",      range:"Touch",            dur:"Conc. 1 hr",    en:"+1 weapon, +1d4 energy damage.",                                           da:"+1 våben, +1d4 elementskade." },
  "Blinding Smite":      { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"+3d8 radiant, CON save or blinded.",                                       da:"+3d8 strålende skade, KON-redning ellers blindet." },
  "Staggering Smite":    { school:"Evocation",   cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"+4d6 psychic, WIS save or disadvantage.",                                  da:"+4d6 psykisk, VIS-redning ellers ulempe." },
  "Holy Weapon":         { school:"Evocation",   cast:"1 bonus action", range:"Touch",            dur:"Conc. 1 hr",    en:"+2d8 radiant on hit.",                                                     da:"+2d8 radiant ved ramt." },
  // ── RANGER ───────────────────────────────────────────────────────────
  "Hunter's Mark":       { school:"Divination",  cast:"1 bonus action", range:"90 ft",            dur:"Conc. 1 hr",    en:"+1d6 on weapon hits vs target.",                                           da:"+1d6 på våbenangrebs mod målet." },
  "Fog Cloud":           { school:"Conjuration", cast:"1 action",       range:"120 ft",           dur:"Conc. 1 hr",    en:"20-ft sphere heavily obscured.",                                           da:"6 m kugle stærkt tilsløret." },
  "Ensnaring Strike":    { school:"Conjuration", cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"STR save or restrained; 1d6 piercing per turn.",                           da:"STY-redning ellers fastholdt; 1d6 gennemborende skade pr. tur." },
  "Hail of Thorns":      { school:"Conjuration", cast:"1 bonus action", range:"Self",             dur:"Conc. 1 min",   en:"DEX save or 1d10 piercing in 5-ft burst.",                                 da:"DEX-redning ellers 1d10 gennemborende skade i et 1,5 m udbrud." },
  "Conjure Barrage":     { school:"Conjuration", cast:"1 action",       range:"Self (60-ft cone)", dur:"Instant",      en:"DEX save or 3d8 weapon-type damage.",                                      da:"DEX-redning ellers 3d8 skade af våbnets type." },
  "Swift Quiver":        { school:"Transmutation",cast:"1 bonus action", range:"Touch",           dur:"Conc. 1 min",   en:"Quiver generates ammo; 2 ranged attacks per bonus action.",                 da:"Koggeret skaber ammunition; 2 afstandsangreb pr. bonushandling." },
  "Lightning Arrow":     { school:"Transmutation",cast:"1 bonus action", range:"Self",            dur:"Conc. 1 min",   en:"Next ranged hit: 4d8 lightning.",                                          da:"Næste afstandsangreb der rammer: 4d8 lyn." },
  "Steel Wind Strike":   { school:"Conjuration", cast:"1 action",       range:"30 ft",            dur:"Instant",       en:"5 targets: 6d10 force each.",                                              da:"Op til 5 mål: 6d10 kraft mod hvert mål." },
  "Cordon of Arrows":    { school:"Transmutation",cast:"1 action",      range:"5 ft",             dur:"8 hours",       en:"4 arrows; DEX save or 1d6 piercing each.",                                 da:"4 pile; DEX-redning ellers 1d6 gennemborende skade." },
  "Conjure Volley":      { school:"Conjuration", cast:"1 action",       range:"150 ft",           dur:"Instant",       en:"40-ft cylinder: DEX save or 8d8 damage.",                                  da:"12 m cylinder: DEX-redning ellers 8d8 skade." },
  "Conjure Woodland Beings":{ school:"Conjuration",cast:"1 action",     range:"60 ft",            dur:"Conc. 1 hr",    en:"Summon fey creatures.",                                                    da:"Kald fey-væsner." },
  "Grasping Vine":       { school:"Conjuration", cast:"1 bonus action", range:"30 ft",            dur:"Conc. 1 min",   en:"2d6 bludgeoning, pull 20 ft.",                                             da:"2d6 slag, træk 6 m." },
  "Tree Stride":         { school:"Conjuration", cast:"1 action",       range:"Self",             dur:"Conc. 1 min",   en:"Teleport between trees of same species.",                                  da:"Teleporter mellem træer af samme art." },
  // ── HIGH-LEVEL SPELLS / EXTRA SRD SPELLS ───────────────────────────────
  "Chain Lightning":    { school:"Evocation",   cast:"1 action",       range:"150 ft",           dur:"Instant",       en:"DEX save or 10d8 lightning; jumps to 3 more targets.",                      da:"DEX-redning ellers 10d8 lyn; springer videre til op til 3 mål." },
  "Conjure Elemental":  { school:"Conjuration", cast:"1 minute",       range:"90 ft",            dur:"Conc. 1 hr",    en:"Summon an elemental spirit to aid you.",                                      da:"Kald en elementarånd, der hjælper dig." },
  "Control Weather":    { school:"Transmutation",cast:"10 minutes",    range:"Self",             dur:"Conc. 8 hr",    en:"Alter weather in a large area around you.",                                   da:"Ændr vejret i et stort område omkring dig." },
  "Delayed Blast Fireball":{ school:"Evocation",cast:"1 action",       range:"150 ft",           dur:"Conc. 1 min",   en:"Growing fireball; DEX save or heavy fire damage.",                            da:"Voksende ildkugle; DEX-redning ellers kraftig ildskade." },
  "Disintegrate":       { school:"Transmutation",cast:"1 action",      range:"60 ft",            dur:"Instant",       en:"DEX save or 10d6+40 force; can turn target to dust.",                         da:"DEX-redning ellers 10d6+40 kraft; kan forvandle målet til støv." },
  "Dominate Monster":   { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 hr",    en:"WIS save or control a creature.",                                             da:"VIS-redning ellers kontrollerer du en skabning." },
  "Earthquake":         { school:"Evocation",   cast:"1 action",       range:"500 ft",           dur:"Conc. 1 min",   en:"Create a severe tremor that damages structures and knocks creatures prone.",   da:"Skab kraftige rystelser, der skader bygninger og vælter skabninger." },
  "Etherealness":       { school:"Transmutation",cast:"1 action",      range:"Self",             dur:"Up to 8 hr",    en:"Step into the Ethereal Plane.",                                               da:"Træd ind på det æteriske plan." },
  "Eyebite":            { school:"Necromancy",  cast:"1 action",       range:"Self",             dur:"Conc. 1 min",   en:"Each turn, affect a creature with sleep, panic, or sickness.",                 da:"På hver tur kan du ramme en skabning med søvn, panik eller sygdom." },
  "Feeblemind":         { school:"Enchantment", cast:"1 action",       range:"150 ft",           dur:"Instant",       en:"INT save or target's mind is shattered.",                                     da:"INT-redning ellers bliver målets sind knust." },
  "Find the Path":      { school:"Divination",  cast:"1 minute",       range:"Self",             dur:"Conc. 1 day",   en:"Learn the shortest route to a known place.",                                  da:"Find den korteste vej til et kendt sted." },
  "Finger of Death":    { school:"Necromancy",  cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"CON save or 7d8+30 necrotic; slain humanoid may rise as zombie.",             da:"KON-redning ellers 7d8+30 nekrotisk; en dræbt humanoid kan rejse sig som zombie." },
  "Fire Storm":         { school:"Evocation",   cast:"1 action",       range:"150 ft",           dur:"Instant",       en:"DEX save or 7d10 fire in chosen 10-ft cubes.",                                da:"DEX-redning ellers 7d10 ild i valgte 3 m kuber." },
  "Foresight":          { school:"Divination",  cast:"1 minute",       range:"Touch",            dur:"8 hours",       en:"Target gains advantage; attacks against it have disadvantage.",               da:"Målet får fordel; angreb mod det har ulempe." },
  "Gate":               { school:"Conjuration", cast:"1 action",       range:"60 ft",            dur:"Conc. 1 min",   en:"Open a portal to another plane.",                                             da:"Åbn en portal til et andet plan." },
  "Glibness":           { school:"Transmutation",cast:"1 action",      range:"Self",             dur:"1 hour",        en:"CHA checks become at least 15; magic cannot detect lies.",                    da:"KAR-checks bliver mindst 15; magi kan ikke afsløre dine løgne." },
  "Globe of Invulnerability":{ school:"Abjuration",cast:"1 action",    range:"Self (10-ft radius)",dur:"Conc. 1 min",  en:"Lower-level spells cannot affect creatures inside the globe.",                da:"Trylleformularer af lavere niveau påvirker ikke skabninger inde i kuglen." },
  "Guards and Wards":   { school:"Abjuration",  cast:"10 minutes",     range:"Touch",            dur:"24 hours",      en:"Ward an area with magical protections.",                                      da:"Beskyt et område med magiske værn." },
  "Heal":               { school:"Evocation",   cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"Restore 70 HP and end blindness, deafness, and disease.",                    da:"Gendan 70 HP og fjern blindhed, døvhed og sygdom." },
  "Incendiary Cloud":   { school:"Conjuration", cast:"1 action",       range:"150 ft",           dur:"Conc. 1 min",   en:"Burning cloud; DEX save or 10d8 fire.",                                      da:"Brændende sky; DEX-redning ellers 10d8 ild." },
  "Locate Creature":    { school:"Divination",  cast:"1 action",       range:"Self",             dur:"Conc. 1 hr",    en:"Sense direction to a known creature within 1,000 ft.",                       da:"Mærk retningen til en kendt skabning inden for 300 m." },
  "Mass Suggestion":    { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"24 hours",      en:"WIS save or up to 12 creatures follow a suggestion.",                        da:"VIS-redning ellers følger op til 12 skabninger et forslag." },
  "Maze":               { school:"Conjuration", cast:"1 action",       range:"60 ft",            dur:"Conc. 10 min",  en:"Banish a creature to a labyrinthine demiplane.",                              da:"Forvis en skabning til et labyrintisk halvplan." },
  "Meteor Swarm":       { school:"Evocation",   cast:"1 action",       range:"1 mile",           dur:"Instant",       en:"Four huge blasts; DEX save or 20d6 fire + 20d6 bludgeoning.",                 da:"Fire enorme nedslag; DEX-redning ellers 20d6 ild + 20d6 slag." },
  "Mind Blank":         { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"24 hours",      en:"Target is protected from psychic damage and mental intrusion.",              da:"Målet beskyttes mod psykisk skade og mental indtrængen." },
  "Mirage Arcane":      { school:"Illusion",    cast:"10 minutes",     range:"Sight",            dur:"10 days",       en:"Transform terrain with a large-scale illusion.",                             da:"Forvandl terræn med en illusion i stor skala." },
  "Mislead":            { school:"Illusion",    cast:"1 action",       range:"Self",             dur:"Conc. 1 hr",    en:"Become invisible and create an illusory double.",                            da:"Bliv usynlig og skab en illusionær dobbeltgænger." },
  "Modify Memory":      { school:"Enchantment", cast:"1 action",       range:"30 ft",            dur:"Conc. 1 min",   en:"WIS save or reshape part of a creature's memory.",                           da:"VIS-redning ellers ændrer du en del af en skabnings hukommelse." },
  "Otto's Irresistible Dance":{ school:"Enchantment",cast:"1 action",  range:"30 ft",            dur:"Conc. 1 min",   en:"Target dances, losing movement and suffering disadvantage.",                  da:"Målet danser, mister bevægelse og får ulempe." },
  "Plane Shift":        { school:"Conjuration", cast:"1 action",       range:"Touch",            dur:"Instant",       en:"Transport creatures to another plane, or banish a creature there.",           da:"Send skabninger til et andet plan, eller forvis en skabning dertil." },
  "Power Word Heal":    { school:"Evocation",   cast:"1 action",       range:"Touch",            dur:"Instant",       en:"Restore all HP and end several conditions.",                                  da:"Gendan alle HP og fjern flere tilstande." },
  "Power Word Kill":    { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"A creature with 100 HP or fewer dies.",                                      da:"En skabning med 100 HP eller mindre dør." },
  "Power Word Stun":    { school:"Enchantment", cast:"1 action",       range:"60 ft",            dur:"Instant",       en:"A creature with 150 HP or fewer is stunned.",                                da:"En skabning med 150 HP eller mindre bliver bedøvet." },
  "Prismatic Spray":    { school:"Evocation",   cast:"1 action",       range:"Self (60-ft cone)", dur:"Instant",       en:"Random colored rays cause varied powerful effects.",                          da:"Tilfældige farvestråler giver forskellige kraftige effekter." },
  "Prismatic Wall":     { school:"Abjuration",  cast:"1 action",       range:"60 ft",            dur:"10 minutes",    en:"Create a layered, multicolored magical wall.",                                da:"Skab en lagdelt, flerfarvet magisk mur." },
  "Regenerate":         { school:"Transmutation",cast:"1 minute",      range:"Touch",            dur:"1 hour",        en:"Target regains HP over time and severed parts can regrow.",                   da:"Målet genvinder HP over tid, og afhuggede kropsdele kan vokse ud igen." },
  "Resurrection":       { school:"Necromancy",  cast:"1 hour",         range:"Touch",            dur:"Instant",       en:"Return a dead creature to life.",                                            da:"Bring en død skabning tilbage til livet." },
  "Reverse Gravity":    { school:"Transmutation",cast:"1 action",      range:"100 ft",           dur:"Conc. 1 min",   en:"Gravity reverses in a cylinder; creatures fall upward.",                     da:"Tyngdekraften vendes i en cylinder; skabninger falder opad." },
  "Shapechange":        { school:"Transmutation",cast:"1 action",      range:"Self",             dur:"Conc. 1 hr",    en:"Transform into powerful creatures while retaining your mind.",               da:"Forvandl dig til mægtige skabninger, mens du bevarer dit sind." },
  "Stoneskin":          { school:"Abjuration",  cast:"1 action",       range:"Touch",            dur:"Conc. 1 hr",    en:"Target gains resistance to nonmagical weapon damage.",                       da:"Målet får modstand mod ikke-magisk våbenskade." },
  "Storm of Vengeance": { school:"Conjuration", cast:"1 action",       range:"Sight",            dur:"Conc. 1 min",   en:"Summon a raging storm with escalating effects.",                             da:"Kald en rasende storm med stadig voldsommere effekter." },
  "Sunbeam":            { school:"Evocation",   cast:"1 action",       range:"Self (60-ft line)", dur:"Conc. 1 min",   en:"CON save or 6d8 radiant and blinded; repeat as action.",                     da:"KON-redning ellers 6d8 strålende skade og blindet; kan gentages som handling." },
  "Sunburst":           { school:"Evocation",   cast:"1 action",       range:"150 ft",           dur:"Instant",       en:"CON save or 12d6 radiant and blinded.",                                     da:"KON-redning ellers 12d6 strålende skade og blindet." },
  "Teleport":           { school:"Conjuration", cast:"1 action",       range:"10 ft",            dur:"Instant",       en:"Transport yourself and willing creatures to a known destination.",            da:"Transportér dig selv og villige skabninger til en kendt destination." },
  "Time Stop":          { school:"Transmutation",cast:"1 action",      range:"Self",             dur:"Instant",       en:"Take 1d4+1 turns while time is stopped for others.",                         da:"Tag 1d4+1 ture, mens tiden står stille for andre." },
  "True Polymorph":     { school:"Transmutation",cast:"1 action",      range:"30 ft",            dur:"Conc. 1 hr",    en:"Transform a creature or object into another form.",                          da:"Forvandl en skabning eller genstand til en anden form." },
  "True Resurrection":  { school:"Necromancy",  cast:"1 hour",         range:"Touch",            dur:"Instant",       en:"Restore a dead creature to life, even without a body.",                      da:"Bring en død skabning tilbage til livet, selv uden et legeme." },
  "True Seeing":        { school:"Divination",  cast:"1 action",       range:"Touch",            dur:"1 hour",        en:"Target gains truesight for 120 ft.",                                          da:"Målet får sandt syn på 36 m." },
  "Wind Walk":          { school:"Transmutation",cast:"1 minute",      range:"30 ft",            dur:"8 hours",       en:"You and allies become cloudlike and fly quickly.",                            da:"Du og allierede bliver skylignende og kan flyve hurtigt." },
  "Wish":               { school:"Conjuration", cast:"1 action",       range:"Self",             dur:"Instant",       en:"The mightiest spell; duplicate spells or reshape reality at DM's discretion.", da:"Den mægtigste formular; kopier trylleformularer eller omskab virkeligheden efter GM's vurdering." },

};

export const CLASS_SPELLS = {
  Wizard:{
    0:["Fire Bolt","Ray of Frost","Shocking Grasp","Mage Hand","Minor Illusion","Prestidigitation","Dancing Lights","Chill Touch"],
    1:["Magic Missile","Shield","Mage Armor","Burning Hands","Charm Person","Sleep","Thunderwave","Detect Magic","Fog Cloud","Witch Bolt"],
    2:["Misty Step","Hold Person","Invisibility","Mirror Image","Scorching Ray","Shatter","Suggestion","Darkness","Flaming Sphere","Silence"],
    3:["Counterspell","Fireball","Fly","Haste","Lightning Bolt","Slow","Fear","Dispel Magic","Vampiric Touch","Animate Dead","Hypnotic Pattern","Major Image","Sending","Remove Curse"],
    4:["Banishment","Greater Invisibility","Ice Storm","Polymorph","Confusion","Blight","Dimension Door","Hallucinatory Terrain"],
    5:["Cone of Cold","Hold Monster","Cloudkill","Dominate Person","Greater Restoration"],
    6:["Disintegrate","Eyebite","True Seeing","Chain Lightning","Globe of Invulnerability"],
    7:["Finger of Death","Prismatic Spray","Teleport","Delayed Blast Fireball","Reverse Gravity"],
    8:["Dominate Monster","Power Word Stun","Feeblemind","Maze","Mind Blank"],
    9:["Wish","Time Stop","Power Word Kill","Meteor Swarm","Prismatic Wall","Gate"],
  },
  Sorcerer:{
    0:["Fire Bolt","Ray of Frost","Shocking Grasp","Mage Hand","Minor Illusion","Prestidigitation","Dancing Lights","Chill Touch"],
    1:["Magic Missile","Shield","Mage Armor","Burning Hands","Charm Person","Sleep","Thunderwave","Fog Cloud","Witch Bolt"],
    2:["Misty Step","Hold Person","Invisibility","Mirror Image","Scorching Ray","Shatter","Suggestion","Darkness","Silence"],
    3:["Counterspell","Fireball","Fly","Haste","Lightning Bolt","Slow","Fear","Dispel Magic","Vampiric Touch","Hypnotic Pattern","Major Image"],
    4:["Banishment","Greater Invisibility","Ice Storm","Polymorph","Confusion","Blight","Dimension Door"],
    5:["Cone of Cold","Hold Monster","Cloudkill","Dominate Person"],
    6:["Disintegrate","Chain Lightning","Globe of Invulnerability"],
    7:["Finger of Death","Prismatic Spray","Teleport","Delayed Blast Fireball","Reverse Gravity"],
    8:["Dominate Monster","Power Word Stun","Incendiary Cloud"],
    9:["Wish","Time Stop","Power Word Kill","Meteor Swarm","Gate"],
  },
  Cleric:{
    0:["Sacred Flame","Guidance","Light","Thaumaturgy","Toll the Dead","Chill Touch"],
    1:["Bless","Bane","Command","Cure Wounds","Guiding Bolt","Healing Word","Inflict Wounds","Shield of Faith","Detect Magic","Detect Evil and Good","Sanctuary","Create or Destroy Water","Purify Food and Drink"],
    2:["Aid","Lesser Restoration","Prayer of Healing","Spiritual Weapon","Hold Person","Silence","Calm Emotions","Enhance Ability","Find Traps","Zone of Truth","Warding Bond","Augury"],
    3:["Animate Dead","Daylight","Dispel Magic","Spirit Guardians","Remove Curse","Revivify","Beacon of Hope","Create Food and Water","Mass Healing Word","Meld into Stone","Speak with Dead","Water Walk","Sending"],
    4:["Death Ward","Freedom of Movement","Guardian of Faith","Banishment","Locate Creature","Divination"],
    5:["Flame Strike","Greater Restoration","Mass Cure Wounds","Raise Dead","Hallow","Commune","Contagion","Dispel Evil and Good","Summon Celestial","Insect Plague"],
  },
  Druid:{
    0:["Druidcraft","Guidance","Produce Flame","Shillelagh","Thorn Whip","Chill Touch"],
    1:["Entangle","Faerie Fire","Goodberry","Speak with Animals","Cure Wounds","Healing Word","Detect Magic","Fog Cloud","Thunderwave","Animal Friendship","Earth Tremor","Purify Food and Drink"],
    2:["Barkskin","Flaming Sphere","Moonbeam","Pass without Trace","Spike Growth","Animal Messenger","Beast Sense","Flame Blade","Gust of Wind","Heat Metal","Locate Object","Locate Animals or Plants","Protection from Poison","Hold Person","Enhance Ability","Find Traps"],
    3:["Call Lightning","Conjure Animals","Plant Growth","Dispel Magic","Daylight","Wind Wall","Meld into Stone","Speak with Plants","Water Walk","Remove Curse"],
    4:["Blight","Dominate Beast","Giant Insect","Hallucinatory Terrain","Ice Storm","Polymorph","Freedom of Movement","Grasping Vine","Conjure Woodland Beings","Locate Creature"],
    5:["Antilife Shell","Insect Plague","Greater Restoration","Commune with Nature","Reincarnate","Tree Stride","Conjure Elemental","Contagion"],
    6:["Heal","True Seeing","Wind Walk","Find the Path","Sunbeam"],
    7:["Fire Storm","Reverse Gravity","Regenerate","Plane Shift","Mirage Arcane"],
    8:["Animal Shapes","Control Weather","Sunburst","Earthquake","Feeblemind"],
    9:["Shapechange","Storm of Vengeance","True Resurrection","Foresight"],
  },
  Bard:{
    0:["Vicious Mockery","Dancing Lights","Minor Illusion","Mage Hand","Light","Prestidigitation","Chill Touch"],
    1:["Dissonant Whispers","Heroism","Healing Word","Cure Wounds","Charm Person","Sleep","Thunderwave","Faerie Fire","Detect Magic","Fog Cloud","Bane","Command","Enthrall"],
    2:["Suggestion","Hold Person","Invisibility","Mirror Image","Silence","Shatter","Calm Emotions","Enhance Ability","Locate Object","Zone of Truth","Animal Messenger","Heat Metal"],
    3:["Hypnotic Pattern","Major Image","Sending","Dispel Magic","Fear","Mass Healing Word","Speak with Dead","Plant Growth"],
    4:["Confusion","Greater Invisibility","Dimension Door","Hallucinatory Terrain","Polymorph","Freedom of Movement","Compulsion"],
    5:["Dominate Person","Hold Monster","Greater Restoration","Raise Dead","Mass Cure Wounds","Modify Memory","Mislead"],
    6:["Eyebite","True Seeing","Guards and Wards","Mass Suggestion","Otto's Irresistible Dance"],
    7:["Mirage Arcane","Teleport","Regenerate","Resurrection","Etherealness"],
    8:["Dominate Monster","Power Word Stun","Feeblemind","Glibness","Mind Blank"],
    9:["True Polymorph","Power Word Kill","Power Word Heal","Prismatic Wall","Foresight"],
  },
  Warlock:{
    0:["Eldritch Blast","Chill Touch","Minor Illusion","Mage Hand","Prestidigitation"],
    1:["Armor of Agathys","Arms of Hadar","Hex","Hellish Rebuke","Witch Bolt","Charm Person","Enthrall"],
    2:["Hold Person","Invisibility","Mirror Image","Misty Step","Darkness","Shatter","Suggestion","Enthrall"],
    3:["Counterspell","Dispel Magic","Fear","Fly","Hypnotic Pattern","Major Image","Remove Curse","Vampiric Touch","Hunger of Hadar"],
    4:["Banishment","Blight","Dimension Door","Hallucinatory Terrain","Compulsion"],
    5:["Hold Monster","Dominate Person","Modify Memory","Cloudkill","Contagion"],
  },
  Paladin:{
    1:["Bless","Command","Cure Wounds","Detect Evil and Good","Detect Magic","Divine Favor","Heroism","Shield of Faith","Compelled Duel","Thunderous Smite","Wrathful Smite","Purify Food and Drink","Sanctuary"],
    2:["Aid","Find Steed","Lesser Restoration","Warding Bond","Zone of Truth","Branding Smite","Prayer of Healing"],
    3:["Aura of Vitality","Crusader's Mantle","Daylight","Dispel Magic","Elemental Weapon","Remove Curse","Revivify","Blinding Smite"],
    4:["Banishment","Death Ward","Locate Creature","Staggering Smite"],
    5:["Greater Restoration","Raise Dead","Dispel Evil and Good","Holy Weapon"],
  },
  Ranger:{
    1:["Hunter's Mark","Fog Cloud","Ensnaring Strike","Hail of Thorns","Cure Wounds","Detect Magic","Speak with Animals","Goodberry","Animal Friendship"],
    2:["Barkskin","Pass without Trace","Spike Growth","Locate Object","Locate Animals or Plants","Silence","Protection from Poison","Cordon of Arrows","Beast Sense","Find Traps"],
    3:["Conjure Animals","Plant Growth","Daylight","Wind Wall","Speak with Plants","Water Walk","Lightning Arrow","Conjure Barrage"],
    4:["Grasping Vine","Locate Creature","Freedom of Movement","Stoneskin","Conjure Woodland Beings"],
    5:["Commune with Nature","Tree Stride","Greater Restoration","Steel Wind Strike","Swift Quiver","Conjure Volley"],
  },
};

export const CLASS_META = {
  Wizard:   { da:"Troldmand",   caster:"full",    spellAbility:"INT" },
  Sorcerer: { da:"Tryllekunstner", caster:"full",  spellAbility:"CHA" },
  Cleric:   { da:"Præst",       caster:"full",     spellAbility:"WIS" },
  Druid:    { da:"Druide",      caster:"full",     spellAbility:"WIS" },
  Bard:     { da:"Skald",       caster:"full",     spellAbility:"CHA" },
  Warlock:  { da:"Heksemester", caster:"warlock",  spellAbility:"CHA" },
  Paladin:  { da:"Paladin",     caster:"half",     spellAbility:"CHA" },
  Ranger:   { da:"Skovløber",   caster:"half",     spellAbility:"WIS" },
};

export const SCHOOL_COLORS = {
  Evocation:    "#f87171",
  Conjuration:  "#60a5fa",
  Enchantment:  "#c084fc",
  Abjuration:   "#34d399",
  Illusion:     "#818cf8",
  Transmutation:"#fb923c",
  Necromancy:   "#94a3b8",
  Divination:   "#fcd34d",
};

export const T = {
  en: {
    title: "SpellbookRPG",
    subtitle: "Browse, filter and build your spell list by class and level.",
    by: "by",
    selectClass: "Choose Class",
    charLevel: "Character Level",
    searchPlaceholder: "Search spells…",
    cantrips: "Cantrips",
    level: "Level",
    noSpells: "No spells found.",
    notCaster: "This class has no spells at this level.",
    selected: "Selected Spells",
    clearAll: "Clear all",
    noSelected: "No spells selected yet.",
    castTime: "Cast",
    range: "Range",
    duration: "Duration",
    school: "School",
    allLevels: "All Levels",
    lang: "DA",
  },
  da: {
    title: "SpellbookRPG",
    subtitle: "Gennemse, filtrer og saml dine formularer efter klasse og niveau.",
    by: "af",
    selectClass: "Vælg klasse",
    charLevel: "Karakterniveau",
    searchPlaceholder: "Søg formularer…",
    cantrips: "Cantrips",
    level: "Niveau",
    noSpells: "Ingen formularer fundet.",
    notCaster: "Denne klasse har ingen formularer på dette niveau.",
    selected: "Valgte formularer",
    clearAll: "Ryd alt",
    noSelected: "Ingen formularer valgt endnu.",
    castTime: "Kasttid",
    range: "Rækkevidde",
    duration: "Varighed",
    school: "Skole",
    allLevels: "Alle niveauer",
    lang: "EN",
  },
};
